name: ESLint

on:
  push:
    branches:
    - main
    paths:
    - 'front-end/**'

jobs:
    eslint:
        name: ESLint
        runs-on: self-hosted
        defaults:
            run:
                working-directory: front-end
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - run: npm ci
            - run: npx eslint .