name: Pylint

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'

jobs:
    test:
        name: Pylint
        runs-on: self-hosted
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        # Already have Python and Pylint installed on the self-hosted runner
        - name: Run Tests
          run: |
            pylint lambda --fail-under=5.5