name: Test Self-hosted Runner for Github Actions

on:
  push:
    branches:
      - test

jobs:
    test:
        name: Test Self-hosted Runner
        runs-on: self-hosted
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Run Tests
          run: |
            ls -a
            echo "Successfully ran!"
